language: php

# list any PHP version you want to test against
php:
  - 5.5

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - mysql -e "create database IF NOT EXISTS bounceapp;" -uroot;
  - mysql -u root bounceapp < bounceapp.sql

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit_mysql.xml --coverage-text

# configure notifications (email, IRC, campfire etc)
notifications:
  email:
    - sw730@uowmail.edu.au
