language: php

# list any PHP version you want to test against
php:
  - 5.5

#before_install:

install:
  - pear install pear/PHP_CodeSniffer

after_install:
  - phpenv rehash

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - mysql -e "create database IF NOT EXISTS bounceapp;" -uroot;
  - mysql -u root bounceapp < bounceapp.sql

# Lint check
script:
  - find . -name "*.php" -exec php -l {} \;
  - phpcs --standard=./build/phpcs.xml .



# configure notifications (email, IRC, campfire etc)
notifications:
  email:
    - sw730@uowmail.edu.au
